# Copyright 2021 The Engula Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Check Code

on:
  pull_request:
  push:
    branches:
      - 'main'


jobs:
  test:
    name: Run tests
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Cargo Cache
      uses: actions/cache@v1
      with:
        path: ~/.cargo
        key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.toml') }}
        restore-keys: |
          ${{ runner.os }}-cargo-${{ hashFiles('Cargo.toml') }}
          ${{ runner.os }}-cargo

    - name: Cargo build
      uses: actions-rs/cargo@v1
      with:
        command: build

    - name: Verify tidy
      run: git diff --exit-code

    - name: Check clippy
      uses: actions-rs/cargo@v1
      with:
        command: clippy
        args: --workspace --tests --all-features -- -D warnings

    - name: Check format
      if: steps.skip-ci.outputs.skip != 'true'
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: --all -- --check

    - name: Cargo test
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --workspace
